import { ContactFormWithTankYou } from "@/components/contact/contact-form-with-tank-you/ContactFormWithTankYou";
import Head from "next/head";
import { ToastContainer } from "react-toastify";

export default function ContactPage() {
  return (
    <>
      <Head>
        <title>Contact Me</title>
        <meta
          name="description"
          content="Contact Me Page of Next.js Blog. Generated by Mitinull."
        />
      </Head>

      <main>
        <ContactFormWithTankYou />
      </main>

      <ToastContainer theme="dark" position="bottom-right" />
    </>
  );
}
