import Head from "next/head";
import { Inter } from "next/font/google";
import { FeaturedPosts } from "@/components/home-page/featured-posts/FeaturedPosts";
import { Hero } from "@/components/home-page/hero/Hero";
import { readFeaturedPosts } from "@/utils/posts-utils/read-featured-posts";

const inter = Inter({ subsets: ["latin"] });

export default function HomePage(props) {
  const { posts } = props;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <FeaturedPosts posts={posts} />
      </main>
    </>
  );
}

export function getStaticProps() {
  const posts = readFeaturedPosts();

  return {
    props: { posts },
  };
}
