import Head from "next/head";
import { Inter } from "next/font/google";
import { FeaturedPosts } from "@/components/home-page/featured-posts/FeaturedPosts";
import { Hero } from "@/components/home-page/hero/Hero";
import { readFeaturedPosts } from "@/utils/posts-utils/read-featured-posts";

const inter = Inter({ subsets: ["latin"] });

export default function HomePage(props) {
  const { posts } = props;

  return (
    <>
      <Head>
        <title>Next.js Blog</title>
        <meta
          name="description"
          content="Next.js Blog Generated by Mitinull."
        />
      </Head>
      <Hero />
      <FeaturedPosts posts={posts} />
    </>
  );
}

export function getStaticProps() {
  const posts = readFeaturedPosts();

  return {
    props: { posts },
  };
}
